# .streamlit/config.toml

[server]
headless = true
port = 8501
enableCORS = false

[runner]
magicEnabled = false
runOnSave = false

# Custom environment variables
[environment]
PYTHONPATH = "/opt/intel/openvino/python/python3.9:$PYTHONPATH"
